/* Kyushu planner: original itinerary, food order and checkbox IDs are preserved. */
(() => {
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const read=(key,fallback)=>{try{const s=localStorage.getItem('kyushu_v2_'+key);return s===null?fallback:JSON.parse(s)}catch{return fallback}};
const write=(key,value)=>{try{localStorage.setItem('kyushu_v2_'+key,JSON.stringify(value));return true}catch{storageWarning();return false}};
function storageWarning(){if($('#storageNotice'))return;const n=document.createElement('div');n.id='storageNotice';n.setAttribute('role','status');n.textContent='浏览器未允许保存；本次可继续使用，关闭页面后修改可能不会保留。';document.body.append(n)}
if(document.documentElement.dataset.storageUnavailable)storageWarning();
const maps=q=>'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(q);
const route=(a,b)=>'https://www.google.com/maps/dir/?api=1&origin='+encodeURIComponent(a)+'&destination='+encodeURIComponent(b)+'&travelmode=transit';
const anchor=(url,label)=>`<a class="action" href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(label)}</a>`;
const source=(url,label)=>`<a class="source" href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(label)} · 核查 2026-10-03</a>`;
const JR='https://www.jrkyushu.co.jp/english/';
const JRTRAIN='https://www.jrkyushu.co.jp/english/train/yufuin_no_mori.html';
const JRPASS='https://www.jrkyushu.co.jp/english/railpass/railpass.html';
const JRFAQ='https://www.jrkyushu.co.jp/english/faq/tr.html';
const NISH='https://www.nishitetsu.jp/en/sightseeing/';
const SHOWA='https://www.showa-bus.jp/';
const ITO='https://www.tablecheck.com/ja/robatano-itookashi/reserve/landing';
const COMICO='https://www.camy.oita.jp/en/museumguide';
const areas=['全部区域','博多站','祇园 / 中洲','天神 / 大名','渡边通 / 春吉','药院 / 白金','平尾','六本松','大濠 / 黑门','由布院','糸岛','待确认分店'];
const priorities=['A 必去','B 想去','C 有空','未分级'];
function select(values,value,attrs=''){return `<select ${attrs}>${values.map(x=>`<option${x===value?' selected':''}>${esc(x)}</option>`).join('')}</select>`}
const transport=[
 {start:'福冈机场国内线（抵达日）',station:'福冈机场站 → 博多 → 渡边通',segments:['机场线至博多约5–10分钟；转七隈线至渡边通，连候车约15–25分钟。','渡边通站步行至 Fukuoka Toei；从落地到入住预留60–90分钟，属规划缓冲。'],pass:'抵达日先单次 / IC；不为这一小段启动多日 JR Pass。',back:'入住后就近吃；不为第一餐排长队。',plan:'晚到或太累：酒店附近轻食 / 便利店；拉面留到市区日。',destination:'Fukuoka Toei Hotel',url:JR},
 {start:'Fukuoka Toei Hotel',station:'药院 / 渡边通；大濠公园站',segments:['酒店 → 药院 / 今泉：步行规划约10–20分钟，依所选早餐分店调整。','天神 → 大濠公园：机场线；步行、候车合计规划约20–30分钟。','大濠公园 → 赤坂 / 大名：地铁后步行，规划约20–30分钟。'],pass:'步行为主先用 IC；若多次乘地铁，再比较单次合计与当日地铁券。',back:'晚餐后回酒店；隔天搭火车，建议21:30前整理好行李。',plan:'下雨：缩短公园，保留天神室内购物＋一顿和牛；太累就只留药院与晚餐。',destination:'Yakuin Station Fukuoka',url:NISH},
 {start:'Fukuoka Toei Hotel → 退房',station:'渡边通 → 博多；第一站：由布院站',segments:['酒店 → 博多站：步行＋七隈线，规划约20–30分钟；另留30–45分钟取票找站台。','由布院之森参考班次：博多09:17 → 由布院11:31，约2小时14分；2027运行日待确认。','抵达后先寄行李；由布院站至 COMICO 官方步行约15分钟。'],pass:'与1/26回程一起比较单买及北九州3日券（1/24–26）；不包含1/27门司港。',back:'今天住由布院，不需回福冈。16:30计划入住；晚餐是否包含及最晚报到另向旅馆确认。',plan:'列车满位：先查 Yufu 或其他可预约班次，再调整午餐；心排太久就吃沿路小吃。不要挤压已预约入馆时间。',destination:'Hakata Station',url:JRTRAIN},
 {start:'Enokiya Ryokan',station:'金鳞湖：步行为主，无需搭车',segments:['旅馆 → 金鳞湖：规划步行约10–20分钟，以导航为准。','湖畔 → Cafe La Ruche → 汤之坪 → 旅馆：短段步行，每段规划5–20分钟。'],pass:'当天无需为镇内活动买交通 pass；多日票仍按连续日计算。',back:'15:00回旅馆休息；18:30为原定生日晚餐目标，餐食及时间尚需确认。',plan:'下雨 / 无晨雾：取消早起，晚些吃早餐；保留湖畔短走与旅馆休息，不补塞景点。',destination:'Kinrin Lake Yufuin',url:COMICO},
 {start:'Enokiya Ryokan → 10:00前退房',station:'由布院站 → 博多 → 渡边通',segments:['退房后向旅馆确认寄存；取回行李＋去车站规划30–45分钟。','由布院 → 博多：特急规划约2小时15分–2小时30分；14:30是目标出发时段，不是已订车次。','博多 → 渡边通 → BASE LAYER：地铁＋步行规划约25–40分钟。'],pass:'若已买1/24启用的3日券，今天最后一天；否则单买回程。',back:'按实际订到的车次倒推取行李；BASE LAYER 15:00后可入住，17:00为计划。',plan:'下雨就提早取行李；如改早班车，先确认座位及改票条件。晚餐只保留一家水炊锅。',destination:'Yufuin Station',url:JRTRAIN},
 {start:'BASE LAYER HOTEL FUKUOKA',station:'渡边通 → 博多 → 小仓 → 门司港',segments:['酒店 → 博多：地铁＋步行规划25–40分钟。','博多 → 小仓：JR特急规划约45–60分钟；换普通列车到门司港约15分钟，另留候车。','门司港站 → Retro 建筑群：步行规划5–15分钟。'],pass:'1/24–26三日券已到期。比较单买与覆盖1/24–28五日券；北九州券不含博多–小仓新干线。',back:'16:30–17:00计划从门司港返程，不是末班车；出发前查当日回程时刻。',plan:'风雨强：缩短海边散步、选室内建筑与咖啡；若一早太累，整天改福冈，门司港保留候补。',destination:'Mojiko Station',url:JRPASS},
 {start:'BASE LAYER HOTEL FUKUOKA',station:'A 糸岛：天神 / 博多巴士站；B 太宰府：西铁药院站',segments:['A 糸岛：酒店 → 天神上车点规划25–40分钟；West Coast Liner 至二见浦约60–90分钟（估算，依班次及堵车）。','A 只排二见浦海岸与海鲜堂；出发前查昭和巴士停靠点、临时改道和往返时刻。','B 太宰府：步行到西铁药院 → 西铁二日市换太宰府线；列车＋换乘规划30–45分钟，酒店门到门约60–75分钟。'],pass:'JR Pass 不含西铁及昭和巴士；先比单买往返，不为二选一同时买两套票。',back:'A 目标15:30–16:00返程，提前确认可搭班次；B 目标16:00–17:00返程。均非末班时间。',plan:'海边风雨大：改太宰府；若持续大雨或太累：留福冈市区。两套方案是二选一，不同日硬塞。',destination:'Nishitetsu Yakuin Station',url:SHOWA},
 {start:'BASE LAYER HOTEL FUKUOKA',station:'渡边通 → 六本松',segments:['酒店步行至渡边通；七隈线到六本松＋步行，门到门规划30–45分钟。','早餐后六本松 → 天神南：七隈线＋步行规划20–30分钟。','天神 / 大名步行串店；COFFEE COUNTY FUKUOKA 与 stock 分店不可当同一地点。'],pass:'市区地铁为主；当天次数确定后再比较日券。',back:'按已确认寿司时段安排购物结束；预约用餐预留15分钟到店缓冲。',plan:'早餐满位：用附近 bakery 替换；寿司排队太长：选同区饭团／面店，原寿司留候补。',destination:'Ropponmatsu Station Fukuoka',url:ITO},
 {start:'BASE LAYER HOTEL FUKUOKA',station:'渡边通 → 博多 / 櫛田神社前',segments:['酒店 → 博多地区：地铁＋步行规划25–40分钟，先锁定早餐分店。','博多 → 天神 / 大名：地铁＋步行规划20–30分钟。','最终晚餐地点确定后再导航；17:00黑田饭是原计划，最新开门时间待确认。'],pass:'购物日先IC／步行；不额外买长途 pass。',back:'17:00前后预留打包时间；晚餐后不再跨区补店。',plan:'排队超过自己设定的30分钟就换同区收藏；只补一顿最想吃的，不追完全部名单。',destination:'Hakata Station',url:NISH},
 {start:'BASE LAYER HOTEL FUKUOKA → 10:00前退房',station:'渡边通 → 博多 → 福冈机场国内线',segments:['七隈线至博多、换机场线；加步行和换乘，门到门规划35–50分钟。','原行程目标11:00左右到机场；具体报到、托运及安检截止以最终机票和航空公司要求为准。','PDF和网页仍是经东京换机场的航班版本；若已改签，先更新机票再使用机场转移计划。'],pass:'单程地铁 / IC即可；按最终航站楼确认下车位置。',back:'回程日不安排跨区早餐；旧航班信息须与最终电子客票核对。',plan:'行李多／下雨可考虑出租车；如果延误，优先机场，取消购物与咖啡。',destination:'Fukuoka Airport Domestic Terminal',url:JR}
];
function transportHTML(t,i){return `<div class="planner"><div class="planner-card lime compact"><span class="eyebrow">DAILY TRANSPORT</span><h3>从酒店到第一站</h3><dl><dt>出发</dt><dd>${esc(t.start)}</dd><dt>车站 / 站点</dt><dd>${esc(t.station)}</dd></dl><ol>${t.segments.map(s=>`<li>${esc(s)}</li>`).join('')}</ol><p><b>Pass 判断</b> · ${esc(t.pass)}</p><p><b>回程 / 时间提醒</b> · ${esc(t.back)}</p><p class="muted">除明确标注的官方参考车次外，时间均为规划估算，包含路段差异；最终班次及末班待出发前核实。</p>${anchor(route(t.start.split(' → ')[0],t.destination),'打开第一段导航')} ${source(t.url,'营运商 / 相关官方资料')}</div><div class="planner-card compact" style="margin-top:12px"><span class="eyebrow">PLAN B</span><p>${esc(t.plan)}</p><label>当天个人备注<textarea data-save="day-note-${i+1}" placeholder="想保留什么？累了先放弃哪一站？">${esc(read('day-note-'+(i+1),''))}</textarea></label></div></div>`}
$$('#days>article').forEach((card,i)=>{card.id='day-'+(i+1);const btn=card.querySelector('.day-head'),body=card.querySelector('.day-body');btn.setAttribute('aria-expanded','false');body.id='day-body-'+(i+1);btn.setAttribute('aria-controls',body.id);btn.addEventListener('click',()=>btn.setAttribute('aria-expanded',String(!body.classList.contains('hidden'))));body.insertAdjacentHTML('beforeend',transportHTML(transport[i],i));});
if(location.hash.startsWith('#day-')){const card=$(location.hash);if(card){card.querySelector('.day-body')?.classList.remove('hidden');card.querySelector('.day-head')?.setAttribute('aria-expanded','true')}}
// Keep every original item and its original completion key; only add structured metadata.
const areaByName={
'FUK COFFEE':'祇园 / 中洲','COFFEE COUNTY FUKUOKA':'药院 / 白金','炉端ノいとおかし':'六本松','Onigiri Gori-chan Tenjin':'天神 / 大名','Ichimujin Watanabe-dori':'渡边通 / 春吉','すき焼き山翔 Sukiyaki Yamasho':'祇园 / 中洲','肉の山翔 Niku no Yamasho':'天神 / 大名','NIKUICHI 薬院焼肉':'药院 / 白金','焼肉 多牛 博多駅南店':'博多站','西新初喜 くうてん博多店':'博多站','葫蘆寿司':'天神 / 大名','糸島海鮮堂 二見ヶ浦本店':'糸岛','博多もつ鍋 おおやま オリエンタルホテル博多店':'博多站','めんたい料理 博多 椒房庵':'博多站','Shin-Shin':'天神 / 大名','一蘭 JR博多シティ店':'博多站','Bread, Espresso & Hakata':'博多站','DACOMECCA':'博多站','Pain Stock Tenjin':'天神 / 大名','THE FULL FULL':'祇园 / 中洲','TruffleBAKERY 天神地下街':'天神 / 大名','MUTSUKA堂':'博多站','Little Stand Daimyo':'天神 / 大名','KUROMON COFFEE':'大濠 / 黑门','HIIRAGI':'六本松','EL TREN COFFEE ROASTERS':'平尾','Abeki':'药院 / 白金','努努雞':'博多站','伊都KING':'博多站','餃子 おそ松 六本松':'六本松'};
let ordinal=0;
const foods=foodGroups.flatMap((g,gi)=>g[1].map(f=>({id:'food-'+(++ordinal),name:f[0],note:f[1],signal:f[2],query:f[3],category:g[0],area:gi===foodGroups.length-1?'由布院':areaByName[f[0]]||'待确认分店',priority:gi===1?'A 必去':'未分级'})));
const foodState=read('foods',{});
function meta(f){const old=foodState[f.id]||{};return {...f,...old}}
function timing(f){if(/早餐|Toast|吐司/.test(f.note))return '早餐 / 午前（规划）';if(/午餐|午餐限定/.test(f.note))return '午餐（规划）';if(/咖啡|Cafe|生乳卷|冰淇淋|蛋糕|甜点|面包/.test(f.note+f.name))return '午后 / 顺路（规划）';return '午餐或晚餐，按预约安排'}
function kind(f){if(/Coffee|COFFEE|咖啡|Cafe|Bakery|早餐|面包|小吃|Dessert/.test(f.category+' '+f.note))return 'Café / 早餐 / 小吃';if(/烧肉|壽喜|寿喜|和牛/.test(f.category))return '和牛 / 烧肉';return '正餐'}
const foodRoot=$('#foodAreas');
if(foodRoot){foodRoot.className='planner';foodRoot.innerHTML=`<div class="planner-card"><div class="planner-row"><h2>找一间，现在想吃的。</h2><a class="action" href="reservations.html">预约清单</a></div><div class="filters"><label>搜索店名 / 收藏原因<input id="foodSearch" type="search" placeholder="例如：明太子、寿司、一个人"></label><label>区域${select(areas,'全部区域','id="areaFilter"')}</label><label>优先级${select(['全部优先级',...priorities],'全部优先级','id="priorityFilter"')}</label><label>餐别${select(['全部餐别','Café / 早餐 / 小吃','和牛 / 烧肉','正餐'],'全部餐别','id="mealFilter"')}</label></div><label class="planner-row" style="justify-content:flex-start"><input type="checkbox" id="onlyUnvisited">只看还没吃过</label><p class="muted">区域是规划分组，请先在 Maps 核对分店；「待确认分店」会保留所有未定位收藏。默认只把你明确列出的三家设为 A，其余由你选择。</p><details><summary>Must Eat by Area · 我的 A 级清单</summary><div class="area-summary" id="areaSummary"></div></details><p id="foodCount" class="counts" role="status"></p></div><div id="foodCards" class="planner-grid" style="margin-top:18px"></div>`;
function renderFoods(){
 const q=$('#foodSearch').value.trim().toLowerCase(),a=$('#areaFilter').value,p=$('#priorityFilter').value,k=$('#mealFilter').value;
 const fs=foods.map(meta).filter(f=>(a==='全部区域'||f.area===a)&&(p==='全部优先级'||f.priority===p)&&(k==='全部餐别'||kind(f)===k)&&(!$('#onlyUnvisited').checked||tripStorage.getItem('kyushu_check_'+f.id)!=='1')&&(!q||(f.name+' '+f.note+' '+(f.personal||'')).toLowerCase().includes(q)));
 $('#foodCount').textContent=`显示 ${fs.length} / ${foods.length} 个收藏 · 独立来源计数沿用原记录`;
 $('#foodCards').innerHTML=fs.map(f=>{
 const done=tripStorage.getItem('kyushu_check_'+f.id)==='1',solo=f.name==='炉端ノいとおかし'?'全席吧台（官方）；1人可订时段见预约页':/Solo friendly|Solo 极友好|Solo 很适合/i.test(f.note)?'原收藏标注可一人食，当前接待待核实':'一人食 / 最低人数待确认';
 const book=f.name==='炉端ノいとおかし'?'TableCheck 预约':/预约/.test(f.note)?'预约规则待核实':'是否接受预约待核实';
 const budget=/和牛|焼肉|烧肉|寿喜|寿司|水炊|牛肠/.test(f.name+f.note)?'个人预留 ¥4,000–10,000+':/咖啡|Coffee|COFFEE|Cafe|面包|蛋糕|甜点/.test(f.name+f.note)?'个人预留 ¥500–1,500':'个人预留 ¥1,000–3,000';
 return `<article class="planner-card ${done?'visited':''}" data-food="${f.id}"><div class="food-title"><input type="checkbox" aria-label="已吃过 ${esc(f.name)}" data-food-done="${f.id}" ${done?'checked':''}><div><h3>${esc(f.name)}</h3><span class="chip accent">${esc(f.priority)}</span><span class="chip">${esc(f.area)}</span>${f.signal.startsWith('🔥')?`<span class="chip">${esc(f.signal)} 独立来源 · 原记录</span>`:''}</div></div><p>${esc(f.note)}</p><p class="muted">${esc(solo)}</p><div class="planner-row">${anchor(maps(f.query),'Maps · 最新时间')}<a class="action" href="reservations.html">${esc(book)}</a></div><details><summary>标签 · 营业提醒 · 我的备注</summary><dl><dt>Best visit</dt><dd>${esc(timing(f))}</dd><dt>预算</dt><dd>${budget}，不是店家报价</dd><dt>休息日 / L.O.</dt><dd>${/星期一休|周一休/.test(f.note)?'原收藏写周一休；尚未官方复核':'待核实；出发当天查 Maps / 官方公告'}</dd></dl><div class="fields"><label>我的优先级${select(priorities,f.priority,`data-food-key="priority" data-id="${f.id}"`)}</label><label>区域 / 分店${select(areas.slice(1),f.area,`data-food-key="area" data-id="${f.id}"`)}</label></div><label style="margin-top:12px">Why I saved this<textarea data-food-key="personal" data-id="${f.id}" placeholder="为了哪道菜？为什么想来？">${esc(f.personal??f.note)}</textarea></label><p class="saved-hint" data-hint="${f.id}" role="status"></p>${f.name==='炉端ノいとおかし'?source(ITO,'TableCheck 店家说明'):''}</details></article>`}).join('')||'<div class="planner-card">没有符合条件的收藏。试试全部区域或清空搜索。</div>';
 const summary=foods.map(meta).filter(f=>f.priority==='A 必去');
 $('#areaSummary').innerHTML=summary.length?areas.slice(1).map(area=>{const group=summary.filter(f=>f.area===area);return group.length?`<div style="padding:10px 0"><b>${esc(area)}</b><p>${group.map(f=>esc(f.name)).join(' · ')}</p></div>`:''}).join(''):'把餐厅设为 A 后，会按区域显示在这里。';
}
['foodSearch','areaFilter','priorityFilter','mealFilter','onlyUnvisited'].forEach(id=>$('#'+id).addEventListener(id==='foodSearch'?'input':'change',renderFoods));
foodRoot.addEventListener('change',e=>{const t=e.target;if(t.dataset.foodDone){tripStorage.setItem('kyushu_check_'+t.dataset.foodDone,t.checked?'1':'0');t.closest('article').classList.toggle('visited',t.checked);if($('#onlyUnvisited').checked)renderFoods();}if(t.dataset.foodKey){const id=t.dataset.id;foodState[id]={...(foodState[id]||{}),[t.dataset.foodKey]:t.value};const ok=write('foods',foodState);const hint=$(`[data-hint="${id}"]`);if(hint)hint.textContent=ok?'已保存在此浏览器':'未能保存';if(t.dataset.foodKey!=='personal')renderFoods();}});
renderFoods();
}
const bookings=[
 {id:'train-out',title:'由布院之森 · 博多 → 由布院',date:'2027-01-24',slot:'09:17参考班次 / 普通车指定席',need:'需取得座位；2027运行日待核实',channel:'JR 九州官网；先决定单买还是用 Rail Pass',when:'预计2026-12-24 10:00 JST / 09:00 MYT 开售（按现行规则推算）',deadline:'建议开售即处理；不是保证有票',url:JR,source:JRFAQ,state:'待开放',legacy:0},
 {id:'train-back',title:'由布院 → 博多 · 回程指定席',date:'2027-01-26',slot:'14:30左右为目标，实际车次待定',need:'建议预订指定席',channel:'JR 九州官网；同一票制安排去回程',when:'预计2026-12-26 10:00 JST / 09:00 MYT 开售（按现行规则推算）',deadline:'建议开售即处理',url:JR,source:JRFAQ,state:'待开放'},
 {id:'itookashi',title:'炉端ノいとおかし · 六本松',date:'2027-01-29',slot:'09:00早餐目标 / 1人',need:'提前网上预约，时段以平台为准',channel:'店家 TableCheck；别选成春吉店',when:'2027-01-29开放窗口尚未确认',deadline:'建议12月开始查看放位，不是店家截止日',url:ITO,source:ITO,state:'待确认',legacy:1},
 {id:'yamasho',title:'すき焼き山翔 · 午餐候选',date:'',slot:'午餐；替换一顿正式和牛，不额外加餐',need:'建议预约；1人套餐及最低人数待确认',channel:'Tabelog 店铺预约页 / 店方公布电话',when:'开放日期及空位待查询',deadline:'建议出发前2–4周查看（个人规划）',url:'https://tabelog.com/fukuoka/A4001/A400101/40071561/',state:'待确认',legacy:2},
 {id:'kawazu',title:'Kawazu Sushi · 本人必吃',date:'2027-01-29',slot:'19:00晚餐目标',need:'先核对准确店名、分店及1人接待',channel:'Maps 确认店铺后进入官方预约／电话',when:'准确店铺尚待确认，不贸然填写预约链接',deadline:'建议出发前2–4周核对（个人规划）',url:maps('Kawazu Sushi Fukuoka'),state:'待确认',legacy:3},
 {id:'birthday',title:'Enokiya · 生日晚餐',date:'2027-01-25',slot:'18:30原定目标',need:'需确认住宿是否含晚餐，可否加购生日餐',channel:'原订房平台联系旅馆',when:'现在可询问；餐食未获确认',deadline:'建议12月先询问；时间以旅馆回复为准',url:maps('Enokiya Ryokan Yufuin'),state:'待确认',legacy:4},
 {id:'yakiniku',title:'热门烧肉 · 只选1–2家',date:'2027-01-23',slot:'19:00目标；大東園 / NIKUICHI / 焼肉 上',need:'先选店、核对1人套餐再订',channel:'选定分店官网／Tabelog／官方电话',when:'店铺选定后确认放位规则',deadline:'建议出发前2–4周查看（个人规划）',url:maps('NIKUICHI Yakuin Fukuoka'),state:'待确认',legacy:5},
 {id:'motsu',title:'牛肠锅 · おおやま / 前田屋',date:'2027-01-28',slot:'19:00目标；两家选一',need:'1人点锅、预约最低人数待核实',channel:'锁定分店后从官方入口预约',when:'订位窗口待确认',deadline:'建议出发前2–4周查看（个人规划）',url:maps('博多もつ鍋 おおやま オリエンタルホテル博多店'),state:'待确认',legacy:6},
 {id:'comico',title:'COMICO ART MUSEUM',date:'2027-01-24',slot:'15:00目标；先订妥火车',need:'建议预约；有余位才可现场入馆',channel:'官网 Online booking',when:'2027日期开放情况以预约日历为准',deadline:'火车落实后订；当前最后入馆16:00',url:COMICO,source:COMICO,state:'待确认'},
 {id:'mizutaki',title:'水炊锅 · 橙 / 華味鳥',date:'2027-01-26',slot:'19:00晚餐目标',need:'核对1人接待及套餐；两家选一',channel:'选定分店官网／官方电话',when:'订位窗口待确认',deadline:'回程列车落实后再订（个人规划）',url:maps('水炊き 橙 福岡'),state:'待确认'},
 {id:'shin',title:'由布院釜饭「心」',date:'2027-01-24',slot:'12:00午餐目标',need:'预约政策待确认；不把排队当成已订',channel:'Maps 确认分店及官方联系方式',when:'若无法预约，依现场排队安排',deadline:'出发前核对；排队太久改沿路小吃',url:maps('Yufu Mabushi Shin Yufuin'),state:'待确认'},
 {id:'moji-seat',title:'门司港往返 · 车票选择',date:'2027-01-27',slot:'09:00从博多出发目标',need:'若选特急指定席可提前购买',channel:'JR 九州官网；普通列车与新干线票价另比',when:'指定席按现行规则预计12/27 09:00 MYT开放',deadline:'先完成单买 / Pass比较，再买票',url:JR,source:JRPASS,state:'待确认'},
 {id:'toei',title:'Fukuoka Toei Hotel · 入住确认',date:'2027-01-22',slot:'22–24 Jan · 2晚',need:'核对晚到入住及订房条款',channel:'原订房平台',when:'附件已有预订；抵达晚间，提前通知',deadline:'建议1/15前确认晚到（个人规划）',url:maps('Fukuoka Toei Hotel'),state:'待确认'},
 {id:'enokiya',title:'Enokiya Ryokan · 入住确认',date:'2027-01-24',slot:'24–26 Jan · 2晚',need:'核对餐食、寄存、入住时间',channel:'原订房平台',when:'附件入住15:00–21:00，退房10:00前',deadline:'附件免费取消：1/21 23:59 JST之前；下单平台再核对',url:maps('Enokiya Ryokan Yufuin'),state:'待确认'},
 {id:'base',title:'BASE LAYER HOTEL · 入住确认',date:'2027-01-26',slot:'26–31 Jan · 5晚',need:'核对入住、寄存、住宿税',channel:'原订房平台',when:'附件入住15:00后，退房10:00前',deadline:'附件免费取消：1/25 15:00 JST之前；下单平台再核对',url:maps('BASE LAYER HOTEL FUKUOKA'),state:'待确认'}
];
const bookingState=read('bookings',{}),statuses=['待确认','待开放','可预约','已申请','已确认','无需预约'];
function bookingMeta(b){return {...b,...(bookingState[b.id]||{})}}
function renderBookings(){const root=$('#reservationApp');if(!root)return;root.innerHTML=`<div class="planner-card lime"><div class="planner-row"><div><span class="eyebrow">RESERVATION TRACKER</span><h2 id="bookingProgress"></h2></div><label>显示${select(['全部','待处理','已确认'],'全部','id="bookingFilter"')}</label></div><p class="muted">原 To-do 打勾记录保留在 More；不会自动当作商家确认。这里的日期提示不会主动推送通知。</p></div><div id="bookingCards" class="planner-grid" style="margin-top:18px"></div>`;drawBookings();$('#bookingFilter').addEventListener('change',drawBookings)}
function drawBookings(){const root=$('#bookingCards');if(!root)return;const done=bookings.map(bookingMeta).filter(b=>b.state==='已确认').length;$('#bookingProgress').textContent=`${done} / ${bookings.length} 项已确认`;
const filter=$('#bookingFilter').value;root.innerHTML=bookings.map(bookingMeta).filter(b=>filter==='全部'||(filter==='已确认'?b.state==='已确认':!['已确认','无需预约'].includes(b.state))).map(b=>`<article class="planner-card ${b.state==='已确认'?'status-done':''}"><div class="planner-row"><span class="chip accent">${esc(b.date||'日期待定')}</span><span class="chip">${esc(b.state)}</span></div><h3>${esc(b.title)}</h3><p>${esc(b.slot)}</p><dl><dt>需要预约？</dt><dd>${esc(b.need)}</dd><dt>方式</dt><dd>${esc(b.channel)}</dd><dt>开放时间</dt><dd>${esc(b.when)}</dd><dt>处理提醒</dt><dd>${esc(b.deadline)}</dd></dl>${b.legacy!==undefined&&tripStorage.getItem('kyushu_check_m'+b.legacy)==='1'?'<p class="muted">原清单已打勾；请根据确认邮件选择实际状态。</p>':''}${anchor(b.url,'查看预约 / 联系入口')}<div class="fields"><label>预约状态${select(statuses,b.state,`data-booking="${b.id}" data-key="state"`)}</label><label>我的处理日期<input type="date" data-booking="${b.id}" data-key="actionDate" value="${esc(b.actionDate||'')}"></label></div><label style="margin-top:12px">确认备注<textarea data-booking="${b.id}" data-key="note" placeholder="人数、时段、是否已收到确认邮件">${esc(b.note||'')}</textarea></label><p class="saved-hint" id="hint-${b.id}" role="status"></p>${b.source?source(b.source,'规则来源'): '<p class="source">预约规则未完整核实；入口仅用于查证，不代表已订。</p>'}</article>`).join('')||'<div class="planner-card">此筛选下暂无预约。</div>';
}
renderBookings();
$('#reservationApp')?.addEventListener('change',e=>{const t=e.target;if(!t.dataset.booking)return;const id=t.dataset.booking;bookingState[id]={...(bookingState[id]||{}),[t.dataset.key]:t.value};const ok=write('bookings',bookingState);if(t.dataset.key==='state')drawBookings();else $('#hint-'+id).textContent=ok?'已保存在此浏览器':'未能保存'});
// More keeps all original flight, hotel and To-do content, then adds compact trip tools.
const more=$('#booking');if(more){more.insertAdjacentHTML('afterbegin',`<div class="planner"><nav class="subnav" aria-label="More sections"><a class="action" href="#booking">Flights + Stay</a><a class="action" href="reservations.html">Reservations</a><a class="action" href="#transport-summary">Transport</a><a class="action" href="#budget">Budget</a><a class="action" href="#checklist">Checklist + Notes</a></nav><div class="notice">航班沿用原网页及附件版本。若已改签，请以最终电子客票为准；此页尚未代入新的航班。住宿确认及取消提醒见 Bookings。</div></div>`);
more.insertAdjacentHTML('beforeend',`<div class="planner planner-stack" style="margin-top:28px"><section id="transport-summary" class="planner-card"><span class="eyebrow">TRANSPORT</span><h2>先比票，再买 Pass。</h2><p>由布院去程1/24、回程1/26、门司港1/27，跨了4个自然日。3日券无法覆盖这三天；比较「单买」「3日券＋门司港单买」「5日券」。</p><p>JR 九州券不含博多–小仓新干线、地铁、西铁及巴士。坐特急去门司港和坐新干线，必须分别比较。</p><div class="planner-row">${anchor(JRPASS,'官方 Pass 范围与价格')}${anchor(JR,'JR 查询 / 购票')}${anchor(NISH,'西铁路线')}${anchor(SHOWA,'昭和巴士时刻')}</div><div class="fields"><label>由布院去程单买 ¥<input type="number" min="0" step="1" data-pass="out"></label><label>由布院回程单买 ¥<input type="number" min="0" step="1" data-pass="back"></label><label>门司港往返单买 ¥<input type="number" min="0" step="1" data-pass="moji"></label><label>3日券＋预约附加费 ¥<input type="number" min="0" step="1" data-pass="three"></label><label>5日券＋预约附加费 ¥<input type="number" min="0" step="1" data-pass="five"></label></div><p id="passResult" class="notice" role="status">填入实际报价后比较；不会把空白当作免费。</p><p class="muted">5日券方案仅在1/24–28使用、门司港选适用列车时可直接比较。所有方案额外的市区交通仍需另付。</p>${source(JRPASS,'适用范围 / 连续日规则')}<details><summary>每天的交通与 Plan B</summary><div class="planner-stack">${transport.map((t,i)=>`<a class="action" href="itinerary.html#day-${i+1}">Day ${i+1} · ${esc(t.station)}</a>`).join('')}</div></details></section><section id="budget" class="planner-card"><span class="eyebrow">BUDGET</span><h2>把预算留给最想吃的。</h2><p class="muted">以下是你的个人预算，不是店家报价。住宿、机票与购物分开，不重复算入每天餐饮。</p><div class="fields"><label>咖啡 / 小吃每天 ¥<input type="number" min="0" data-budget="cafe"></label><label>午餐每天 ¥<input type="number" min="0" data-budget="lunch"></label><label>一般晚餐每天 ¥<input type="number" min="0" data-budget="dinner"></label><label>其他早餐 / 零食每天 ¥<input type="number" min="0" data-budget="breakfast"></label><label>市区交通每天 ¥<input type="number" min="0" data-budget="local"></label><label>计入预算天数<input type="number" min="1" max="30" data-budget="days"></label><label>长途交通总预留 ¥<input type="number" min="0" data-budget="intercity" placeholder="填单买合计或 Pass 组合总价"></label><label>生日 / 升级餐额外预留 ¥<input type="number" min="0" data-budget="special"></label><label>购物总预留 ¥<input type="number" min="0" data-budget="shopping"></label><label>机票＋住宿固定费用 RM<input type="number" min="0" step="0.01" data-budget="fixed" placeholder="填已确认总额"></label><label>计划汇率：100 JPY = RM<input type="number" min="0.01" step="0.01" data-budget="rate" placeholder="自行填写，不是即时汇率"></label></div><div id="budgetTotal" class="notice" role="status"></div><p class="muted">若住宿含早餐或生日晚餐，请调低相关餐饮预算。长途交通空白时，总数会标明尚未计入。</p></section><section id="checklist" class="planner-card"><span class="eyebrow">READY TO GO</span><h2>Checklist + Personal Notes</h2><div id="packingChecks"></div><label style="margin-top:18px">旅行笔记 / Backup plans<textarea data-save="trip-notes" placeholder="想买的东西、紧急联系人、下雨想去的地方……">${esc(read('trip-notes',''))}</textarea></label><p class="muted">打勾、优先级、预算及备注只保存在当前浏览器，不会自动跨设备同步。</p><button class="action" id="exportNotes" type="button">导出我的记录</button></section></div>`);
const pack=['最终电子客票与东京转机机场核对','酒店入住与生日晚餐确认','由布院往返指定席 / 取票方式','护照与旅行保险','eSIM / 漫游','IC卡与少量现金','充电器、转换插头、耳机','冬衣、雨具、防滑鞋','出发前一晚查天气、店休日及回程时刻'];
$('#packingChecks').innerHTML=pack.map((s,i)=>`<div class="check-row"><input type="checkbox" id="pack-${i}" data-save="pack-${i}" ${read('pack-'+i,false)?'checked':''}><label for="pack-${i}">${esc(s)}</label></div>`).join('');
const pass=read('pass',{});$$('[data-pass]').forEach(t=>{t.value=pass[t.dataset.pass]??'';t.addEventListener('input',()=>{pass[t.dataset.pass]=t.value;write('pass',pass);calcPass()})});
function amount(v){return v!==''&&v!==undefined&&Number.isFinite(Number(v))&&Number(v)>=0?Number(v):null}
function calcPass(){const v=Object.fromEntries(Object.entries(pass).map(([k,x])=>[k,amount(x)]));if(['out','back','moji','three','five'].some(k=>v[k]==null)){$('#passResult').textContent='填齐五个实际报价后比较；空白表示尚未核实。';return}const options=[['单买',v.out+v.back+v.moji],['3日券＋门司港单买',v.three+v.moji],['5日券',v.five]].sort((a,b)=>a[1]-b[1]);$('#passResult').textContent=options.map(x=>`${x[0]} ¥${x[1].toLocaleString()}`).join(' / ')+`。按所填报价，${options[0][0]}最低；先确认座位、适用列车及取消规则。`}
calcPass();
const budget=read('budget',{cafe:1000,lunch:2000,dinner:4000,breakfast:800,local:800,days:10,intercity:'',special:6000,shopping:20000,fixed:'',rate:''});
$$('[data-budget]').forEach(t=>{t.value=budget[t.dataset.budget]??'';t.addEventListener('input',()=>{budget[t.dataset.budget]=t.value;write('budget',budget);calcBudget()})});
function calcBudget(){const n=k=>Math.max(0,Number(budget[k])||0),per=n('cafe')+n('lunch')+n('dinner')+n('breakfast')+n('local'),count=Math.min(30,Math.max(1,n('days'))),total=per*count+n('intercity')+n('special')+n('shopping');let msg=`每天参考 ¥${per.toLocaleString()} · ${count}天可变预算 ¥${total.toLocaleString()}`;if(amount(budget.intercity)==null)msg+='（未计长途交通）';if(n('rate')>0){const rm=total*n('rate')/100;msg+=` · 约 RM${rm.toFixed(2)}`;if(amount(budget.fixed)!=null)msg+=`；加固定费用总计 RM${(rm+n('fixed')).toFixed(2)}`}else msg+='。填写计划汇率后显示 RM。';$('#budgetTotal').textContent=msg}
calcBudget();
$('#exportNotes').addEventListener('click',()=>{const data={version:2,exportedAt:new Date().toISOString(),records:{}};try{for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(key?.startsWith('kyushu_'))data.records[key]=localStorage.getItem(key)}}catch{storageWarning();return}const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='kyushu-my-records.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)});
}
// Overview: useful shortcuts and real completion, preserving the existing visual design.
const ov=$('#overview');if(ov){ov.insertAdjacentHTML('afterbegin',`<div class="planner planner-card lime" style="margin:8px 0 22px"><div class="planner-row"><div><span class="eyebrow">YOUR TRIP, READY WHEN YOU ARE</span><h3 style="margin:6px 0">先订好重点，其他慢慢来。</h3><p class="muted">由布院去程预计12/24、回程12/26开放 · MYT 09:00</p></div><div class="planner-row"><a class="action primary" href="reservations.html">查看预约清单</a><a class="action" href="booking.html#budget">预算与交通</a></div></div></div>`)}
const totalChecks=$$('.persist').length,doneChecks=$$('.persist:checked').length;
$$('#overview article').filter(x=>x.textContent.includes('Trip completion')).forEach(x=>{const num=x.querySelector('.text-5xl');if(num)num.textContent=Math.round(doneChecks/Math.max(1,totalChecks)*100)+'%';const caption=x.querySelector('.mb-2');if(caption)caption.textContent='清单完成 · 此浏览器'});
// All editable text is inserted with escaping, never evaluated as HTML.
document.addEventListener('change',e=>{const t=e.target;if(t.dataset.save)write(t.dataset.save,t.type==='checkbox'?t.checked:t.value)});
$$('a[target="_blank"]').forEach(a=>a.rel='noopener noreferrer');
})();
